.INCLUDE "m128def.inc"

	CBI DDRB, 2 ; PORTB.2 = INPUT
	SBI	PORTB, 2;

	LDI R16, 0xff
	OUT DDRC, R16

	SBI DDRD, 3

AGAIN:
	SBIS PINB, 2 ; if PB2 = 1(High), skip
	RJMP AGAIN
	LDI R16, 0x45
	OUT PORTC, R16
	SBI PORTD, 3
	CBI PORTD, 3